### ISSUE TITLE
Empty htseq-count output

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#12]
About 10 samples, all from Mendota, ran through the read counting script via htseq-count with no errors, but the output file is empty. Any ideas why?

**Comment by sstevens2** [comment]
Is there low coverage in those samples?  Maybe it just didn't find any hits?

**Comment by joshamilton** [comment]
What script are you using? Even if there are no hits, htseq-count should report the number of reads that didn't align. The output file should never be empty. Can I access the bam and gff files that are causing the error?

**Comment by alexlinz** [comment]
The sam files are too huge to get off gluster (picked 3 examples to send you and the zipped archive is 22GB...) but I will be saving as bam next time around per Sarah's suggestion in a different issue thread. I was using sam because I needed that format for the kraken classification of unmapped reads, but I don't think that will be major step in my final workflow anyway. 

The sam files look normal from what I can see, and htseq-count is reporting unmapped reads for other samples. I'm using the same gff file for all samples, so I don't think that's causing the problem. Here's the script I'm using. I will send you the problem bam files if I still have this problem after changing upstream steps.

```{bash, eval = F}
#!/bin/bash
#Make a count table of mapped reads

#Transfer data from gluster
cp /mnt/gluster/amlinz/GEODES_mapping_concat/$1.all.sam .
cp /mnt/gluster/amlinz/python.tar.gz .


#Unzip programs
tar xzf python.tar.gz
tar xvf samtools.tar.gz
gzip -d mapping_database.gff.gz

#Update the path variable
mkdir home
export PATH=$(pwd)/python/bin:$(pwd)/samtools/bin:$PATH
export HOME=$(pwd)/home

#Manipulate the output
samtools view -b -S $1.all.sam > $1.bam 
samtools sort -o $1.sorted $1.bam 
samtools index $1.sorted.bam

#Count reads
python ./python/bin/htseq-count -f bam -r pos -s no -a 0 -t CDS -i locus_tag -m intersection-strict -o $1.CDS.sam $1.sorted.bam mapping_database.gff > $1.CDS.out

#Save output to gluster. Using cp/rm instead of mv so it will overwrite old output in gluster if I need to restart the job.
cp $1.CDS.out /mnt/gluster/amlinz/GEODES_mapping_summaries/
rm $1.CDS.out

#Clean up
rm -rf python
rm -rf samtools
rm *.sam
rm *.bam
rm *.bai
rm mapping_database*
rm *.tar.gz
```

**Comment by alexlinz** [comment]
Switched to FeatureCount from HTSeq-count and no longer have this issue.
