### ISSUE TITLE
Splitting fastq files

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#3]
In theory, each sequence in the fastq file is represent by 4 lines (header, forward sequence, + sign, reverse sequence). So when I split my fastq files to run on CHTC, I split in numbers divisible by 4. However, a handful of the split files produced errors saying that sequences were cutoff. Any ideas why this could be, or suggestions of programs/commands specific for splitting fastq files?

**Comment by sstevens2** [comment]
Not sure if you are looking for answers from me, let me know if you don't want them. Did you check that it isn't hard wrapping the sequence or quality lines sometimes? Those don't strictly have to be one line since it knows that they must be between the header lines pattern
If you know the number of reads in each file, Think you can use getreads.sh from bbtools to split them.
http://seqanswers.com/forums/showthread.php?t=58221

**Comment by alexlinz** [comment]
You're ahead of the game! I'm planning on having people read through the repo and think about my issues before showing preliminary results at small group meeting on Mar 6. So yes, answers are welcome. I'll look into hard wrapping, thanks!

**Comment by sstevens2** [comment]
Yeah I think I was automatically subscribed since I'm an admin for the McMahon github.  I'll unwatch and only look for mentions and when directed though ;). Added a program suggestion to above comment.

**Comment by sstevens2** [comment]
Good idea for lab meeting though!

**Comment by alexlinz** [comment]
The getreads.sh script looks like what I need, I'll give it a try and let you know how it goes!

**Comment by alexlinz** [comment]
I think I figured out the issue - no line wrapping, but there are a handful of blank lines in the fastq files. This meant that splitting the file in increments of 4 cut off some sequences, and also caused getreads.sh to throw an error. I diagnosed the issue using this program: http://genome.sph.umich.edu/wiki/FastQValidator

Below is my code to fix the blank lines+ split the files properly. I'll test this on several files in parallel and close the issue if everything works. Technically, I could go back to splitting by line numbers divisible by 4 now that I've removed blank lines, but I'm more comfortable using getreads.sh in case there are end of file characters or other things I was unintentionally truncating.

But this brings up a different question - why do I have blank lines in my files? These were output by sortmerna.

 ```{bash, eval = F}
#Get the files
tar -xvzf BBMap_36.99.tar.gz
cp /mnt/gluster/amlinz/GEODES_nonrRNA_concat/GEODES001_nonrRNA.fastq.gz .
gzip -d GEODES001_nonrRNA.fastq.gz

#Remove empty lines
sed -i '/^$/d' GEODES001_nonrRNA.fastq

#Count the number of reads in the file
maxreads=$((`wc -l < GEODES001_nonrRNA.fastq` / 8 - 1))
startpoints=$(seq 0 500000 $maxreads)

#The first line above counts the number of lines, then divides by 4, giving 6168763. But each sequence is paired - when I give getreads.sh IDS from 0-100000, it reads 2000000 reads and quits between 3000000 and 4000000. So I want to divide this by 2 again, or in other words, divide the line count by 8 to get the number of paired reads. Also, getreads.sh starts counting at 0, so I subtract by 1.
#The next line counts in increments from 500000 to the number of reads in the file. This should give me one million reads (paired) per file.

for num in $startpoints;
  do endpoint=$(($num + 499999));
  bbmap/getreads.sh in=GEODES001_nonrRNA.fastq id=$num-$endpoint out=GEODES001_nonrRNA_$endpoint.fastq overwrite=T;
  done

#I have exactly 168763 reads left in the last file, and 1000000 in the other 6.
```
