### ISSUE TITLE
rRNA ratios

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#4]
When I compared my rRNA/other RNA ratios to those produced by the JGI, JGI had much higher percentages of rRNA in their samples (~90% rRNA for them vs anywhere from 12-60% in mine). Could it be that the JGI already removed rRNA from the "filter-MTF.fastq" samples that I'm using, and I'm picking up additional rRNA sequences by using a different program or database? Or am I not catching enough rRNA reads?

**Comment by joshamilton** [comment]
I think the QC reports are for the raw reads, not the "filter-MTF.fastq" files that you are using. The QC report gives the total number of reads, you should look at the raw and filtered reads to see which file the QC report describes.

**Comment by alexlinz** [comment]
The file name on header of the QC report doesn't include the "filter-MTF" tag and the number of reads matches the unfiltered samples, so I think you're right. Thanks!
