### ISSUE TITLE
Sporadic .sam merging error

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/geodes#9]
Every once in a while during the 02merge_mapped_results step, I get an error on one of the small .sam files that says:
[sam_header_line_parse] expected '@XY', got [@BFFGGGGGGGGGGGDGGGGD>FGGCGGGGGGGGGGGGGGGGEGGGGGBGFGGGDGGGGGGGEAGGGGGGGGGGEGCGGGFGGGGCGGGGGGBGGGGG:CGGGGGGGGGEGBEG<BGGEG/DDEGGGGGDD=EGEGD>GGGGGGGGG     4       *       0       0       *       *       0   0*       AS:i:0  XS:i:0]
Hint: The header tags must be tab-separated.
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!

This file gets skipped and and is not included in the merge. Any ideas why?

**Comment by sstevens2** [comment]
Can you link or add the path to the 02merge_mapped_results step file in this repo?  I can't seem to find it to look at your commands.

Have you seen the link below?  Seems like you might need the `-h` flag when you make the sam file from the bam file? (but again I couldn't find the acutal commands) or the `-r` flag to bwa might be needed.
http://seqanswers.com/forums/showthread.php?t=13882

**Comment by alexlinz** [comment]
No longer merging SAM files, so this is no longer an issue
